services:
    python:
        container_name: python
        build:
            context: ./python/files
            dockerfile: Dockerfile
        ports:
            - "${PORT}:16000"
        networks:
            knowledge_graph:
                aliases:
                    - python

networks:
    knowledge_graph:
        name: knowledge_graph
        driver: bridge
